services:
  server:
    image: wink:latest
    command:
      - /bin/sh
      - -c
      - |
        ls build/samples/
        ./build/src/WinkServer serve -a 10.0.0.2:42000 build/samples/
    expose:
      - "42000:42000/udp"
      - "64000:64000/udp"
      - "64001:64001/udp"
      - "64002:64002/udp"
    networks:
      winknet:
        ipv4_address: 10.0.0.2
    working_dir: /Wink

  publisher:
    image: wink:latest
    command:
      - /bin/sh
      - -c
      - |
        sleep 1
        ./build/src/Wink start -a 10.0.0.3:42001 -f true pubsub/Publisher 10.0.0.2:64000
    expose:
      - "42001:42001/udp"
    networks:
      winknet:
        ipv4_address: 10.0.0.3
    working_dir: /Wink

  subscriber1:
    image: wink:latest
    command:
      - /bin/sh
      - -c
      - |
        sleep 2
        ./build/src/Wink start -a 10.0.0.4:42001 -f true pubsub/Subscriber 10.0.0.2:64001 10.0.0.2:64000
    expose:
      - "42001:42001/udp"
    networks:
      winknet:
        ipv4_address: 10.0.0.4
    working_dir: /Wink

  subscriber2:
    image: wink:latest
    command:
      - /bin/sh
      - -c
      - |
        sleep 3
        ./build/src/Wink start -a 10.0.0.5:42001 -f true pubsub/Subscriber 10.0.0.2:64002 10.0.0.2:64000
    expose:
      - "42001:42001/udp"
    networks:
      winknet:
        ipv4_address: 10.0.0.5
    working_dir: /Wink

  client:
    image: wink:latest
    command:
      - /bin/sh
      - -c
      - |
        sleep 10
        ./build/src/Wink send -a 10.0.0.6:42001 10.0.0.2:64000 "publish Hello"
        sleep 10
        ./build/src/Wink send -a 10.0.0.6:42002 10.0.0.2:64000 "publish World"
        sleep 10
        ./build/src/Wink send -a 10.0.0.6:42003 10.0.0.2:64000 exit
    expose:
      - "42001:42001/udp"
      - "42002:42002/udp"
      - "42003:42003/udp"
    networks:
      winknet:
        ipv4_address: 10.0.0.6
    working_dir: /Wink

networks:
  winknet:
    driver: bridge
    internal: true
    ipam:
     config:
       - subnet: 10.0.0.0/16
         gateway: 10.0.0.1
